"use client"

import { use, useRef } from 'react';
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { toPng } from 'html-to-image';
import { 
    Download, 
    Share2, 
    BarChart3, 
    ExternalLink, 
    FileText, 
    Zap,
    Lock
} from 'lucide-react';
import { Button } from "@/components/ui/button";
import ChartRenderer from '@/components/ChartRenderer';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { useStackApp } from "@stackframe/stack";
import Loader from '@/components/Loader';

export default function SharedDashboard({ params }) {
    const stack = useStackApp();
    const user = stack.useUser();
    const resolvedParams = use(params);
    const dashboardId = resolvedParams.dashboardId;
    const dashboardRef = useRef(null);

    const dashboard = useQuery(api.dashboards.getById, { id: dashboardId });
    const convexUser = useQuery(api.users.getUserByStackId, user ? { stackId: user.id } : "skip");

    const handleDownloadImage = async () => {
        if (dashboardRef.current === null) return;
        
        try {
            const dataUrl = await toPng(dashboardRef.current, { cacheBust: true, backgroundColor: '#f8fafc' });
            const link = document.createElement('a');
            link.download = `${dashboard?.name || 'catalyst-dashboard'}.png`;
            link.href = dataUrl;
            link.click();
        } catch (err) {
            console.error('Failed to capture dashboard', err);
        }
    };

    if (dashboard === undefined) return <Loader />;
    
    // Privacy Check: Compare Convex User ID with Dashboard Owner ID
    const isOwner = convexUser && dashboard && convexUser._id === dashboard.userId;
    const isPrivate = dashboard && !dashboard.isPublic;
    const accessDenied = isPrivate && !isOwner;

    if (dashboard === null || accessDenied) {
        return (
            <div className="h-screen flex flex-col items-center justify-center bg-slate-50 p-6 text-center">
                <div className="w-20 h-20 bg-white rounded-3xl border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center mb-8">
                    <Lock className="w-10 h-10 text-slate-400" />
                </div>
                <h1 className="text-3xl font-black text-slate-900 uppercase tracking-tighter mb-4">
                    {accessDenied ? "Access Denied" : "Private Dashboard"}
                </h1>
                <p className="text-slate-500 max-w-sm font-bold uppercase tracking-tight text-xs"> 
                    {accessDenied 
                        ? "This dashboard is private. Only the owner can view it." 
                        : "This dashboard does not exist or has been removed."}
                </p>
                <Button onClick={() => window.location.href = '/'} className="mt-8 bg-black text-white rounded-none border-4 border-black font-black uppercase tracking-widest px-8">Return Home</Button>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 md:p-8 selection:bg-emerald-500/10">
            {/* Toolbar */}
            <div className="max-w-7xl mx-auto mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white dark:bg-slate-900 border-4 border-black p-4 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 flex items-center justify-center">
                        <img src="/logo.png" alt="Catalyst" className="w-full h-full object-contain" />
                    </div>
                    <div>
                        <h1 className="text-lg font-black text-slate-900 dark:text-white leading-tight uppercase tracking-tighter">{dashboard.name}</h1>
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Generated by Catalyst Spreadsheet Intelligence</p>
                    </div>
                </div>
                <div className="flex items-center gap-2">
                    <Button 
                        onClick={handleDownloadImage}
                        variant="outline" 
                        className="rounded-none border-2 border-black font-black uppercase tracking-widest text-[10px] h-10 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-none transition-all"
                    >
                        <Download className="w-4 h-4 mr-2" />
                        Export PNG
                    </Button>
                    <Button 
                        disabled={!dashboard.isPublic}
                        onClick={() => {
                            if (!dashboard.isPublic) return;
                            navigator.clipboard.writeText(window.location.href);
                            toast.success("Link copied to clipboard!");
                        }}
                        className={cn(
                            "rounded-none border-2 border-black font-black uppercase tracking-widest text-[10px] h-10 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-none transition-all",
                            dashboard.isPublic 
                                ? "bg-emerald-600 hover:bg-emerald-700 text-white border-black" 
                                : "bg-slate-100 text-slate-400 border-slate-300 cursor-not-allowed opacity-50 shadow-none hover:translate-x-0 hover:translate-y-0"
                        )}
                    >
                        <Share2 className="w-4 h-4 mr-2" />
                        {dashboard.isPublic ? "Share Link" : "Private Link Only"}
                    </Button>
                </div>
            </div>

            {/* Dashboard Canvas */}
            <div ref={dashboardRef} className="max-w-7xl mx-auto space-y-6 pb-8">
                {/* Strategic Intel Hero - Front Page of the Report */}
                <div className="bg-black text-white p-10 border-4 border-black shadow-[12px_12px_0px_0px_rgba(16,185,129,1)] flex flex-col gap-8">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                            <span className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-400 italic">Agentic Intel Report</span>
                        </div>
                        <div className="flex items-center gap-4">
                            <span className="text-[9px] font-black uppercase tracking-widest text-slate-500">
                                {new Date(dashboard._creationTime).toLocaleDateString()}
                            </span>
                            <div className="h-4 w-[1px] bg-slate-800" />
                            <span className="text-[9px] font-black uppercase tracking-widest text-slate-500">
                                Catalyst v1.2
                            </span>
                        </div>
                    </div>

                    <div className="space-y-4">
                        <h1 className="text-5xl md:text-6xl font-black uppercase tracking-tighter leading-[0.85] max-w-4xl">
                            {dashboard.name}
                        </h1>
                        <p className="text-lg font-bold text-slate-400 max-w-2xl leading-snug uppercase tracking-tight italic opacity-80">
                            Real-time data insights and visual reporting. 
                            Powered by Catalyst AI to help you find hidden trends, spot risks, and make smarter decisions with your spreadsheets.
                        </p>
                    </div>

                    <div className="pt-6 border-t border-slate-800 flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center border border-white/10">
                                <Zap className="w-4 h-4 text-emerald-400" />
                            </div>
                            <span className="text-[10px] font-black uppercase tracking-widest text-white/50">Catalyst AI Engine</span>
                        </div>
                        <div className="flex gap-1">
                            {[1, 2, 3].map(i => (
                                <div key={i} className="w-1.5 h-1.5 rounded-full bg-emerald-500/20" />
                            ))}
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {dashboard.config.filter(w => w.type !== 'summary').map((widget, i) => {
                        const size = widget.size || 'small';
                        const gridClass = {
                            small: "md:col-span-1 lg:col-span-1",
                            medium: "md:col-span-2 lg:col-span-2",
                            large: "md:col-span-2 lg:col-span-3"
                        }[size] || "md:col-span-1 lg:col-span-1";

                        return (
                            <div 
                                key={i} 
                                className={cn(
                                    "bg-white dark:bg-slate-900 border-4 border-black p-6 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] flex flex-col",
                                    gridClass
                                )}
                            >
                            <div className="flex items-center justify-between mb-6">
                                <div className="flex items-center gap-3">
                                    <div className="w-8 h-8 bg-slate-100 dark:bg-slate-800 border-2 border-black flex items-center justify-center">
                                        {widget.type === 'chart' ? <BarChart3 className="w-4 h-4" /> : <FileText className="w-4 h-4" />}
                                    </div>
                                    <h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight">{widget.title}</h3>
                                </div>
                            </div>
                            
                            {widget.type === 'chart' ? (
                                <ChartRenderer config={widget.chartConfig} />
                            ) : (
                                <div className="prose prose-sm dark:prose-invert max-w-none">
                                    <p className="text-slate-600 dark:text-slate-400 font-medium leading-relaxed italic">{widget.notes}</p>
                                </div>
                            )}
                        </div>
                    );
                })}
                </div>

                {/* Dynamic Footer Insight - Powered by Catalyst AI Summary Widget */}
                {dashboard.config.find(w => w.type === 'summary') && (
                    <div className="p-8 bg-black text-white border-4 border-black shadow-[12px_12px_0px_0px_rgba(16,185,129,1)]">
                        <div className="flex items-center gap-2 mb-4">
                            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                            <h4 className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-400">AI Intelligence Summary</h4>
                        </div>
                        <p className="text-lg font-bold leading-tight uppercase tracking-tight max-w-4xl italic">
                            {dashboard.config.find(w => w.type === 'summary').notes}
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}
