"use client"

import { use, useRef, useState } from 'react';
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { toPng } from 'html-to-image';
import { 
    Download, 
    Share2, 
    BarChart3, 
    ExternalLink, 
    FileText, 
    Zap,
    Lock,
    Sun,
    Moon,
    Monitor,
    Layout,
    Palette,
    TrendingUp
} from 'lucide-react';
import { Button } from "@/components/ui/button";
import ChartRenderer from '@/components/ChartRenderer';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { useStackApp } from "@stackframe/stack";
import Loader from '@/components/Loader';

export default function SharedDashboard({ params }) {
    const stack = useStackApp();
    const user = stack.useUser();
    const resolvedParams = use(params);
    const dashboardId = resolvedParams.dashboardId;
    const dashboardRef = useRef(null);
    const [theme, setTheme] = useState('catalyst'); // catalyst, executive, midnight

    const dashboard = useQuery(api.dashboards.getById, { id: dashboardId });
    const convexUser = useQuery(api.users.getUserByStackId, user ? { stackId: user.id } : "skip");

    const handleDownloadImage = async () => {
        if (dashboardRef.current === null) return;
        
        const bgColor = {
            catalyst: '#f8fafc',
            executive: '#ffffff',
            midnight: '#020617',
            emerald: '#022c22',
            cyberpunk: '#07020d',
            aurora: '#090d16',
            corporate: '#f1f5f9',
            minimalist: '#fcfbf9'
        }[theme];

        try {
            const dataUrl = await toPng(dashboardRef.current, { 
                cacheBust: true, 
                backgroundColor: bgColor,
                style: {
                    borderRadius: '0px'
                }
            });
            const link = document.createElement('a');
            link.download = `${dashboard?.name || 'catalyst-dashboard'}-${theme}.png`;
            link.href = dataUrl;
            link.click();
        } catch (err) {
            console.error('Failed to capture dashboard', err);
        }
    };

    if (dashboard === undefined) return <Loader />;
    
    // Privacy Check: Compare Convex User ID with Dashboard Owner ID
    const isOwner = convexUser && dashboard && convexUser._id === dashboard.userId;
    const isPrivate = dashboard && !dashboard.isPublic;
    const accessDenied = isPrivate && !isOwner;

    if (dashboard === null || accessDenied) {
        return (
            <div className="h-screen flex flex-col items-center justify-center bg-slate-50 p-6 text-center">
                <div className="w-20 h-20 bg-white rounded-3xl border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center mb-8">
                    <Lock className="w-10 h-10 text-slate-400" />
                </div>
                <h1 className="text-3xl font-black text-slate-900 uppercase tracking-tighter mb-4">
                    {accessDenied ? "Access Denied" : "Private Dashboard"}
                </h1>
                <p className="text-slate-500 max-w-sm font-bold uppercase tracking-tight text-xs"> 
                    {accessDenied 
                        ? "This dashboard is private. Only the owner can view it." 
                        : "This dashboard does not exist or has been removed."}
                </p>
                <Button onClick={() => window.location.href = '/'} className="mt-8 bg-black text-white rounded-none border-4 border-black font-black uppercase tracking-widest px-8">Return Home</Button>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 md:p-8 selection:bg-emerald-500/10">
            {/* Toolbar */}
            <div className="max-w-7xl mx-auto mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white dark:bg-slate-900 border-4 border-black p-4 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 flex items-center justify-center">
                        <img src="/logo.png" alt="Catalyst" className="w-full h-full object-contain" />
                    </div>
                    <div>
                        <h1 className="text-lg font-black text-slate-900 dark:text-white leading-tight uppercase tracking-tighter">{dashboard.name}</h1>
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Generated by Catalyst Conversational Data Agent</p>
                    </div>
                </div>
                <div className="flex items-center gap-2">
                    <div className="flex flex-wrap items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-xl mr-4 border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('catalyst')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'catalyst' ? "bg-black text-white" : "text-slate-500 hover:bg-black/5"
                            )}
                        >
                            Catalyst
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('executive')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'executive' ? "bg-white text-black border-2 border-black" : "text-slate-500 hover:bg-black/5"
                            )}
                        >
                            Executive
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('midnight')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'midnight' ? "bg-indigo-600 text-white" : "text-slate-500 hover:bg-black/5"
                            )}
                        >
                            Midnight
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('emerald')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'emerald' ? "bg-emerald-600 text-white" : "text-slate-500 hover:bg-emerald-500/10"
                            )}
                        >
                            Emerald
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('cyberpunk')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'cyberpunk' ? "bg-fuchsia-600 text-white" : "text-slate-500 hover:bg-fuchsia-500/10"
                            )}
                        >
                            Cyberpunk
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('aurora')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'aurora' ? "bg-cyan-600 text-white" : "text-slate-500 hover:bg-cyan-500/10"
                            )}
                        >
                            Aurora
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('corporate')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'corporate' ? "bg-slate-700 text-white" : "text-slate-500 hover:bg-slate-500/10"
                            )}
                        >
                            Corporate BI
                        </Button>
                        <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setTheme('minimalist')}
                            className={cn(
                                "h-8 px-3 rounded-lg font-black uppercase text-[9px] transition-all",
                                theme === 'minimalist' ? "bg-amber-600 text-white" : "text-slate-500 hover:bg-amber-600/10"
                            )}
                        >
                            Warm Minimalist
                        </Button>
                    </div>

                    <Button 
                        onClick={handleDownloadImage}
                        variant="outline" 
                        className="rounded-none border-2 border-black font-black uppercase tracking-widest text-[10px] h-10 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-none transition-all"
                    >
                        <Download className="w-4 h-4 mr-2" />
                        Export {theme.toUpperCase()} PNG
                    </Button>
                    <Button 
                        disabled={!dashboard.isPublic}
                        onClick={() => {
                            if (!dashboard.isPublic) return;
                            navigator.clipboard.writeText(window.location.href);
                            toast.success("Link copied to clipboard!");
                        }}
                        className={cn(
                            "rounded-none border-2 border-black font-black uppercase tracking-widest text-[10px] h-10 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-none transition-all",
                            dashboard.isPublic 
                                ? "bg-emerald-600 hover:bg-emerald-700 text-white border-black" 
                                : "bg-slate-100 text-slate-400 border-slate-300 cursor-not-allowed opacity-50 shadow-none hover:translate-x-0 hover:translate-y-0"
                        )}
                    >
                        <Share2 className="w-4 h-4 mr-2" />
                        {dashboard.isPublic ? "Share Link" : "Private Link Only"}
                    </Button>
                </div>
            </div>

            {/* Dashboard Canvas */}
            <div ref={dashboardRef} className={cn(
                "max-w-7xl mx-auto space-y-6 pb-12 transition-all duration-500",
                theme === 'midnight' ? "bg-slate-950 p-6 rounded-[2rem] border-4 border-indigo-500/20 shadow-2xl" : "",
                theme === 'emerald' ? "bg-emerald-950 p-6 rounded-[2rem] border-4 border-emerald-500/20 shadow-2xl" : "",
                theme === 'cyberpunk' ? "bg-[#07020d] p-6 rounded-[2rem] border-4 border-fuchsia-500/20 shadow-[0_0_50px_-10px_rgba(217,70,239,0.15)]" : "",
                theme === 'aurora' ? "bg-slate-950 p-6 rounded-[2rem] border-4 border-white/10 shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]" : "",
                theme === 'corporate' ? "bg-slate-100 p-8 rounded-none border border-slate-200/80 shadow-sm" : "",
                theme === 'minimalist' ? "bg-[#faf8f5] p-8 rounded-[2.5rem] border border-stone-200/60 shadow-sm" : ""
            )}>
                {/* Strategic Intel Hero */}
                <div className={cn(
                    "p-10 transition-all duration-500 flex flex-col gap-8",
                    theme === 'catalyst' && "bg-black text-white border-4 border-black shadow-[12px_12px_0px_0px_rgba(16,185,129,1)]",
                    theme === 'executive' && "bg-white text-slate-900 border-4 border-slate-100 shadow-xl rounded-[2.5rem]",
                    theme === 'midnight' && "bg-slate-900 text-white border-4 border-indigo-500 shadow-[0_0_50px_-12px_rgba(99,102,241,0.5)] rounded-[2.5rem]",
                    theme === 'emerald' && "bg-emerald-900 text-emerald-50 border-4 border-emerald-500/30 shadow-[12px_12px_0px_0px_rgba(234,179,8,0.2)] rounded-[2.5rem]",
                    theme === 'cyberpunk' && "bg-[#110924] text-white border-4 border-fuchsia-500 shadow-[0_0_40px_-5px_rgba(217,70,239,0.3)] rounded-[2.5rem]",
                    theme === 'aurora' && "bg-white/5 text-white border border-white/10 shadow-[0_8px_32px_0_rgba(31,38,135,0.07)] backdrop-blur-xl rounded-[2.5rem]",
                    theme === 'corporate' && "bg-[#0b1329] text-white rounded-none border border-slate-800 shadow-[0_2px_8px_rgba(0,0,0,0.15)]",
                    theme === 'minimalist' && "bg-[#1c1917] text-stone-100 rounded-[2.5rem] border border-stone-850 shadow-[0_4px_24px_rgba(28,25,23,0.1)]"
                )}>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className={cn(
                                "w-2 h-2 rounded-full animate-pulse",
                                theme === 'executive' ? "bg-blue-600" :
                                theme === 'emerald' ? "bg-amber-400" :
                                theme === 'cyberpunk' ? "bg-fuchsia-500" :
                                theme === 'aurora' ? "bg-cyan-400" :
                                theme === 'corporate' ? "bg-sky-400" :
                                theme === 'minimalist' ? "bg-amber-500" :
                                "bg-emerald-500"
                            )} />
                            <span className={cn(
                                "text-[10px] font-black uppercase tracking-[0.4em] italic",
                                theme === 'executive' ? "text-blue-600" :
                                theme === 'emerald' ? "text-amber-400" :
                                theme === 'cyberpunk' ? "text-fuchsia-400" :
                                theme === 'aurora' ? "text-cyan-400" :
                                theme === 'corporate' ? "text-sky-400" :
                                theme === 'minimalist' ? "text-amber-500" :
                                "text-emerald-400"
                            )}>Agentic Intel Report</span>
                        </div>
                        <div className="flex items-center gap-4">
                            <span className="text-[9px] font-black uppercase tracking-widest text-slate-500">
                                {new Date(dashboard._creationTime).toLocaleDateString()}
                            </span>
                            <div className="h-4 w-[1px] bg-slate-800" />
                            <span className="text-[9px] font-black uppercase tracking-widest text-slate-500">
                                Catalyst v1.2
                            </span>
                        </div>
                    </div>
 
                    <div className="space-y-4">
                        <h1 className={cn(
                            "text-5xl md:text-6xl font-black uppercase tracking-tighter leading-[0.85] max-w-4xl transition-all",
                            theme === 'executive' ? "text-slate-900" :
                            theme === 'emerald' ? "text-emerald-50" :
                            theme === 'minimalist' ? "text-stone-100" :
                            "text-white"
                        )}>
                            {dashboard.name}
                        </h1>
                        <p className={cn(
                            "text-lg font-bold max-w-2xl leading-snug uppercase tracking-tight italic opacity-80",
                            theme === 'executive' ? "text-slate-500" :
                            theme === 'emerald' ? "text-emerald-200" :
                            theme === 'cyberpunk' ? "text-fuchsia-200/80" :
                            theme === 'aurora' ? "text-cyan-100/70" :
                            theme === 'corporate' ? "text-slate-300" :
                            theme === 'minimalist' ? "text-stone-300" :
                            "text-slate-400"
                        )}>
                            Real-time data insights and visual reporting. 
                            Powered by Catalyst AI to help you find hidden trends, spot risks, and make smarter decisions with your spreadsheets.
                        </p>
                    </div>
 
                    <div className={cn(
                        "pt-6 border-t flex items-center justify-between",
                        theme === 'executive' ? "border-slate-100" :
                        theme === 'emerald' ? "border-emerald-800/40" :
                        theme === 'aurora' ? "border-white/10" :
                        theme === 'corporate' ? "border-slate-800" :
                        theme === 'minimalist' ? "border-stone-800" :
                        "border-slate-800"
                    )}>
                        <div className="flex items-center gap-2">
                            <div className={cn(
                                "w-8 h-8 rounded-lg flex items-center justify-center border",
                                theme === 'executive' ? "bg-slate-50 border-slate-200" :
                                theme === 'emerald' ? "bg-emerald-950/40 border-emerald-800/40" :
                                theme === 'cyberpunk' ? "bg-[#1f0d3d] border-fuchsia-800/40" :
                                theme === 'aurora' ? "bg-white/5 border-white/10" :
                                theme === 'corporate' ? "bg-[#16223f] border-slate-700" :
                                theme === 'minimalist' ? "bg-stone-900 border-stone-850" :
                                "bg-white/5 border-white/10"
                            )}>
                                <Zap className={cn(
                                    "w-4 h-4", 
                                    theme === 'executive' ? "text-blue-600" :
                                    theme === 'emerald' ? "text-amber-400" :
                                    theme === 'cyberpunk' ? "text-fuchsia-400" :
                                    theme === 'aurora' ? "text-cyan-400" :
                                    theme === 'corporate' ? "text-sky-400" :
                                    theme === 'minimalist' ? "text-amber-500" :
                                    "text-emerald-400"
                                )} />
                            </div>
                            <span className={cn(
                                "text-[10px] font-black uppercase tracking-widest",
                                theme === 'executive' ? "text-slate-400" :
                                theme === 'emerald' ? "text-emerald-400/80" :
                                theme === 'cyberpunk' ? "text-fuchsia-400/80" :
                                theme === 'aurora' ? "text-cyan-400/80" :
                                theme === 'corporate' ? "text-sky-400/80" :
                                theme === 'minimalist' ? "text-amber-500/85" :
                                "text-white/50"
                            )}>Catalyst AI Engine</span>
                        </div>
                        <div className="flex gap-1">
                            {[1, 2, 3].map(i => (
                                <div key={i} className={cn(
                                    "w-1.5 h-1.5 rounded-full",
                                    theme === 'executive' ? "bg-blue-200" :
                                    theme === 'emerald' ? "bg-amber-400/20" :
                                    theme === 'cyberpunk' ? "bg-fuchsia-500/20" :
                                    theme === 'aurora' ? "bg-cyan-500/20" :
                                    theme === 'corporate' ? "bg-sky-500/25" :
                                    theme === 'minimalist' ? "bg-amber-500/25" :
                                    "bg-emerald-500/20"
                                )} />
                            ))}
                        </div>
                    </div>
                </div>

                {/* Dynamic KPI & Chart Rows */}
                {(() => {
                    const kpiWidgets = dashboard.config.filter(w => 
                        w.type === 'metric' || 
                        w.type === 'kpi' || 
                        (w.type === 'chart' && (!w.chartConfig || !Array.isArray(w.chartConfig.data) || w.chartConfig.data.length === 0))
                    );
                    
                    const otherWidgets = dashboard.config.filter(w => 
                        w.type !== 'summary' && 
                        !(w.type === 'metric' || w.type === 'kpi' || (w.type === 'chart' && (!w.chartConfig || !Array.isArray(w.chartConfig.data) || w.chartConfig.data.length === 0)))
                    );

                    return (
                        <div className="flex flex-col gap-6 w-full">
                            {/* KPI Metrics Row */}
                            {kpiWidgets.length > 0 && (
                                <div className={cn(
                                    "grid gap-6 w-full transition-all duration-500",
                                    kpiWidgets.length === 1 && "grid-cols-1",
                                    kpiWidgets.length === 2 && "grid-cols-1 md:grid-cols-2",
                                    kpiWidgets.length === 3 && "grid-cols-1 md:grid-cols-3 lg:grid-cols-3",
                                    kpiWidgets.length >= 4 && "grid-cols-1 md:grid-cols-2 lg:grid-cols-4"
                                )}>
                                    {kpiWidgets.map((widget, i) => {
                                        const rawVal = widget.value || widget.chartConfig?.value || widget.notes || (widget.chartConfig?.data && widget.chartConfig.data[0] && (widget.chartConfig.data[0].value || widget.chartConfig.data[0][widget.chartConfig.yAxis])) || "";
                                        const valStr = String(rawVal).trim();
                                        const titleLower = (widget.title || "").toLowerCase();
                                        const subtextLower = (widget.subtext || "").toLowerCase();

                                        const isCurrency = valStr.includes('$') || 
                                                           titleLower.includes('revenue') || 
                                                           titleLower.includes('sales') || 
                                                           titleLower.includes('profit') || 
                                                           titleLower.includes('cost') ||
                                                           titleLower.includes('value') ||
                                                           subtextLower.includes('sales') ||
                                                           subtextLower.includes('revenue');

                                        const isPercentage = valStr.includes('%') || 
                                                             titleLower.includes('percent') || 
                                                             titleLower.includes('rate') || 
                                                             titleLower.includes('margin %');

                                        // Advanced Multi-Tier KPI Formatting Engine
                                        let parsedNum = NaN;
                                        let cleanStr = valStr.replace(/[$,]/g, "").toLowerCase();
                                        if (cleanStr.endsWith('k')) {
                                            parsedNum = Number(cleanStr.slice(0, -1)) * 1000;
                                        } else if (cleanStr.endsWith('m')) {
                                            parsedNum = Number(cleanStr.slice(0, -1)) * 1000000;
                                        } else if (cleanStr.endsWith('b')) {
                                            parsedNum = Number(cleanStr.slice(0, -1)) * 1000000000;
                                        } else {
                                            parsedNum = Number(cleanStr);
                                        }

                                        let valueStr = valStr;
                                        if (!isNaN(parsedNum)) {
                                            if (isPercentage) {
                                                valueStr = `${parsedNum.toFixed(1)}%`;
                                            } else {
                                                let formatted = "";
                                                if (Math.abs(parsedNum) >= 1000000000) {
                                                    formatted = `${(parsedNum / 1000000000).toFixed(2)}B`;
                                                } else if (Math.abs(parsedNum) >= 1000000) {
                                                    formatted = `${(parsedNum / 1000000).toFixed(2)}M`;
                                                } else if (Math.abs(parsedNum) >= 10000 && isCurrency) {
                                                    formatted = `${(parsedNum / 1000).toFixed(1)}K`;
                                                } else {
                                                    formatted = parsedNum.toLocaleString(undefined, { maximumFractionDigits: 2 });
                                                }
                                                valueStr = isCurrency ? `$${formatted}` : formatted;
                                            }
                                        }

                                        const metricLabel = isCurrency 
                                            ? "Financial Metric" 
                                            : isPercentage 
                                                ? "Performance Rate" 
                                                : "Volume / Count";

                                        const trendColor = widget.trendType === 'positive' 
                                            ? "text-emerald-600 bg-emerald-50 dark:bg-emerald-950/30 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-900/30" 
                                            : widget.trendType === 'negative' 
                                                ? "text-rose-600 bg-rose-50 dark:bg-rose-950/30 dark:text-rose-400 border border-rose-200 dark:border-rose-900/30" 
                                                : "text-slate-600 bg-slate-50 dark:bg-slate-800 dark:text-slate-400 border border-slate-200 dark:border-slate-750";

                                        return (
                                            <div 
                                                key={`kpi-${i}`} 
                                                className={cn(
                                                    "p-6 flex flex-col transition-all duration-500",
                                                    theme === 'catalyst' && "bg-white dark:bg-slate-900 border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]",
                                                    theme === 'executive' && "bg-white border-2 border-slate-100 shadow-lg rounded-[2rem]",
                                                    theme === 'midnight' && "bg-slate-900 border-2 border-indigo-500/30 shadow-[0_4px_20px_-5px_rgba(0,0,0,0.35)] rounded-[2rem]",
                                                    theme === 'emerald' && "bg-[#06281e] border-2 border-emerald-500/30 shadow-[4px_4px_0px_0px_rgba(234,179,8,0.15)] rounded-[2rem]",
                                                    theme === 'cyberpunk' && "bg-[#110924] border-2 border-fuchsia-500/40 shadow-[0_0_20px_-5px_rgba(217,70,239,0.25)] rounded-[2rem]",
                                                    theme === 'aurora' && "bg-white/5 border border-white/10 shadow-xl backdrop-blur-xl rounded-[2rem]",
                                                    theme === 'corporate' && "bg-white border border-slate-200 rounded-none shadow-[2px_2px_4px_rgba(0,0,0,0.02)]",
                                                    theme === 'minimalist' && "bg-white border border-stone-200/80 shadow-[0_4px_20px_-4px_rgba(120,110,90,0.06)] rounded-[2rem]"
                                                )}
                                            >
                                                <div className="flex items-center justify-between mb-6">
                                                    <div className="flex items-center gap-3">
                                                        <div className={cn(
                                                            "w-8 h-8 border-2 flex items-center justify-center transition-all",
                                                            theme === 'catalyst' ? "bg-slate-100 dark:bg-slate-800 border-black text-slate-900 dark:text-white" : 
                                                            theme === 'executive' ? "bg-blue-50 border-blue-200 rounded-lg text-blue-600" :
                                                            theme === 'emerald' ? "bg-emerald-950/50 border-emerald-500/30 rounded-lg text-amber-400" :
                                                            theme === 'cyberpunk' ? "bg-fuchsia-500/10 border-fuchsia-500/30 rounded-lg text-fuchsia-400" :
                                                            theme === 'aurora' ? "bg-cyan-500/10 border-cyan-500/30 rounded-lg text-cyan-400" :
                                                            theme === 'corporate' ? "bg-slate-50 border-slate-200 rounded-none text-sky-600" :
                                                            theme === 'minimalist' ? "bg-amber-50 border-stone-200 rounded-xl text-amber-700" :
                                                            "bg-indigo-500/10 border-indigo-500/50 rounded-lg text-indigo-400"
                                                        )}>
                                                            <TrendingUp className="w-4 h-4" />
                                                        </div>
                                                        <h3 className={cn(
                                                            "text-sm font-black uppercase tracking-tight transition-colors",
                                                            theme === 'midnight' || theme === 'emerald' || theme === 'cyberpunk' || theme === 'aurora' ? "text-white" :
                                                            theme === 'corporate' ? "text-slate-700 font-bold" :
                                                            theme === 'minimalist' ? "text-stone-800 font-extrabold" :
                                                            "text-slate-900 dark:text-white"
                                                        )}>{widget.title}</h3>
                                                    </div>
                                                </div>
                                                
                                                <div className="flex-1 flex flex-col justify-between py-2 relative pl-4 border-l-4 transition-all duration-500" style={{ borderLeftColor: theme === 'minimalist' ? (isCurrency ? '#d97706' : isPercentage ? '#b45309' : '#78716c') : (isCurrency ? '#10b981' : isPercentage ? '#f59e0b' : '#3b82f6') }}>
                                                    <div className="flex items-center justify-between mb-4">
                                                        <span className={cn(
                                                            "text-[8px] font-black uppercase tracking-widest",
                                                            theme === 'midnight' ? "text-indigo-400/80" :
                                                            theme === 'emerald' ? "text-emerald-400/80" :
                                                            theme === 'cyberpunk' ? "text-fuchsia-400/80" :
                                                            theme === 'aurora' ? "text-cyan-400/80" :
                                                            theme === 'corporate' ? "text-sky-600 font-bold" :
                                                            theme === 'minimalist' ? "text-amber-750 font-extrabold" :
                                                            "text-slate-400"
                                                        )}>
                                                            {metricLabel}
                                                        </span>
                                                        {widget.trend && (
                                                            <span className={cn(
                                                                "px-2 py-0.5 rounded-full text-[8px] font-black uppercase tracking-wider",
                                                                trendColor
                                                            )}>
                                                                {widget.trend}
                                                            </span>
                                                        )}
                                                    </div>
 
                                                    {/* Giant Bold Value Accent (Dynamic Scale & Overflow-Proof) */}
                                                    <div className="my-2 overflow-hidden pr-2">
                                                        <span className={cn(
                                                            "font-black tracking-tight uppercase block leading-none transition-all duration-500 truncate",
                                                            valueStr.length > 12 ? "text-xl md:text-2xl" :
                                                            valueStr.length > 9 ? "text-2xl md:text-3xl" :
                                                            valueStr.length > 7 ? "text-3xl md:text-4xl" :
                                                            "text-4xl md:text-5xl",
                                                            theme === 'midnight' || theme === 'emerald' || theme === 'cyberpunk' || theme === 'aurora' ? "text-white" :
                                                            theme === 'corporate' ? "text-slate-800 font-black" :
                                                            theme === 'minimalist' ? "text-stone-900 font-black" :
                                                            "text-slate-900 dark:text-white"
                                                        )}>
                                                            {valueStr || "N/A"}
                                                        </span>
                                                    </div>
 
                                                    <div className="mt-2">
                                                        <span className={cn(
                                                            "text-[9px] font-black uppercase tracking-[0.2em] block transition-colors",
                                                            theme === 'midnight' || theme === 'emerald' || theme === 'cyberpunk' || theme === 'aurora' ? "text-slate-400" :
                                                            theme === 'corporate' ? "text-slate-450 text-[8px]" :
                                                            theme === 'minimalist' ? "text-stone-500 font-semibold" :
                                                            "text-slate-500 dark:text-slate-400"
                                                        )}>
                                                            {widget.subtext || "Key Performance Indicator"}
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            )}

                            {/* Main Charts & Visualizations Row (Flexbox Auto-Stretch) */}
                            {otherWidgets.length > 0 && (
                                <div className="flex flex-wrap gap-6 w-full transition-all duration-500">
                                    {otherWidgets.map((widget, i) => {
                                        const size = widget.size || 'small';
                                        
                                        // Dynamic Flexbox sizing: Auto-stretches to fill empty row space!
                                        const flexClass = {
                                            small: "flex-1 lg:flex-[1_1_21%] min-w-[290px]",
                                            medium: "w-full lg:w-[48%] lg:flex-[2_2_48%] min-w-[320px]",
                                            large: "w-full min-w-full flex-shrink-0"
                                        }[size] || "flex-1 min-w-[290px]";

                                        return (
                                            <div 
                                                key={`other-${i}`} 
                                                className={cn(
                                                    "p-6 flex flex-col transition-all duration-500",
                                                    flexClass,
                                                    theme === 'catalyst' && "bg-white dark:bg-slate-900 border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]",
                                                    theme === 'executive' && "bg-white border-2 border-slate-100 shadow-lg rounded-[2rem]",
                                                    theme === 'midnight' && "bg-slate-900 border-2 border-indigo-500/30 shadow-[0_4px_20px_-5px_rgba(0,0,0,0.35)] rounded-[2rem]",
                                                    theme === 'emerald' && "bg-[#06281e] border-2 border-emerald-500/30 shadow-[4px_4px_0px_0px_rgba(234,179,8,0.15)] rounded-[2rem]",
                                                    theme === 'cyberpunk' && "bg-[#110924] border-2 border-fuchsia-500/40 shadow-[0_0_20px_-5px_rgba(217,70,239,0.25)] rounded-[2rem]",
                                                    theme === 'aurora' && "bg-white/5 border border-white/10 shadow-xl backdrop-blur-xl rounded-[2rem]",
                                                    theme === 'corporate' && "bg-white border border-slate-200 rounded-none shadow-[2px_2px_4px_rgba(0,0,0,0.02)]",
                                                    theme === 'minimalist' && "bg-white border border-stone-200/80 shadow-[0_4px_20px_-4px_rgba(120,110,90,0.06)] rounded-[2rem]"
                                                )}
                                            >
                                                <div className="flex items-center justify-between mb-6">
                                                    <div className="flex items-center gap-3">
                                                        <div className={cn(
                                                            "w-8 h-8 border-2 flex items-center justify-center transition-all",
                                                            theme === 'catalyst' ? "bg-slate-100 dark:bg-slate-800 border-black text-slate-900 dark:text-white" : 
                                                            theme === 'executive' ? "bg-blue-50 border-blue-200 rounded-lg text-blue-600" :
                                                            theme === 'emerald' ? "bg-emerald-950/50 border-emerald-500/30 rounded-lg text-amber-400" :
                                                            theme === 'cyberpunk' ? "bg-fuchsia-500/10 border-fuchsia-500/30 rounded-lg text-fuchsia-400" :
                                                            theme === 'aurora' ? "bg-cyan-500/10 border-cyan-500/30 rounded-lg text-cyan-400" :
                                                            theme === 'corporate' ? "bg-slate-50 border-slate-200 rounded-none text-sky-600" :
                                                            theme === 'minimalist' ? "bg-stone-50 border-stone-200 rounded-xl text-stone-600" :
                                                            "bg-indigo-500/10 border-indigo-500/50 rounded-lg text-indigo-400"
                                                        )}>
                                                            {widget.type === 'chart' ? (
                                                                <BarChart3 className="w-4 h-4" />
                                                            ) : (
                                                                <FileText className="w-4 h-4" />
                                                            )}
                                                        </div>
                                                        <h3 className={cn(
                                                            "text-sm font-black uppercase tracking-tight transition-colors",
                                                            theme === 'midnight' || theme === 'emerald' || theme === 'cyberpunk' || theme === 'aurora' ? "text-white" :
                                                            theme === 'corporate' ? "text-slate-700 font-bold" :
                                                            theme === 'minimalist' ? "text-stone-800 font-extrabold" :
                                                            "text-slate-900 dark:text-white"
                                                        )}>{widget.title}</h3>
                                                    </div>
                                                </div>
                                                
                                                {widget.type === 'chart' && widget.chartConfig && Array.isArray(widget.chartConfig.data) && widget.chartConfig.data.length > 0 ? (
                                                    <ChartRenderer config={widget.chartConfig} theme={theme} />
                                                ) : (
                                                    <div className="prose prose-sm dark:prose-invert max-w-none">
                                                        <p className="text-slate-600 dark:text-slate-400 font-medium leading-relaxed italic">{widget.notes}</p>
                                                    </div>
                                                )}
                                            </div>
                                        );
                                    })}
                                </div>
                            )}
                        </div>
                    );
                })()}

                {dashboard.config.find(w => w.type === 'summary') && (
                    <div className={cn(
                        "p-8 transition-all duration-500",
                        theme === 'catalyst' && "bg-black text-white border-4 border-black shadow-[12px_12px_0px_0px_rgba(16,185,129,1)]",
                        theme === 'executive' && "bg-white text-slate-900 border-4 border-slate-100 shadow-xl rounded-[2.5rem]",
                        theme === 'midnight' && "bg-indigo-900 text-white border-4 border-indigo-500 shadow-2xl rounded-[2.5rem]",
                        theme === 'emerald' && "bg-emerald-900 text-emerald-50 border-4 border-emerald-500/30 shadow-[12px_12px_0px_0px_rgba(234,179,8,0.2)] rounded-[2.5rem]",
                        theme === 'cyberpunk' && "bg-[#110924] text-white border-4 border-fuchsia-500 shadow-[0_0_40px_-5px_rgba(217,70,239,0.3)] rounded-[2.5rem]",
                        theme === 'aurora' && "bg-white/5 text-white border border-white/10 shadow-[0_8px_32px_0_rgba(31,38,135,0.07)] backdrop-blur-xl rounded-[2.5rem]",
                        theme === 'corporate' && "bg-[#0b1329] text-white rounded-none border border-slate-800 shadow-[0_2px_8px_rgba(0,0,0,0.15)]",
                        theme === 'minimalist' && "bg-[#1c1917] text-stone-100 rounded-[2.5rem] border border-stone-850 shadow-[0_4px_24px_rgba(28,25,23,0.1)]"
                    )}>
                        <div className="flex items-center gap-2 mb-4">
                            <div className={cn(
                                "w-2 h-2 rounded-full animate-pulse",
                                theme === 'executive' ? "bg-blue-600" :
                                theme === 'emerald' ? "bg-amber-400" :
                                theme === 'cyberpunk' ? "bg-fuchsia-500" :
                                theme === 'aurora' ? "bg-cyan-400" :
                                theme === 'corporate' ? "bg-sky-400" :
                                theme === 'minimalist' ? "bg-amber-500" :
                                "bg-emerald-500"
                            )} />
                            <h4 className={cn(
                                "text-[10px] font-black uppercase tracking-[0.4em]",
                                theme === 'executive' ? "text-slate-400" :
                                theme === 'emerald' ? "text-amber-400" :
                                theme === 'cyberpunk' ? "text-fuchsia-400" :
                                theme === 'aurora' ? "text-cyan-400" :
                                theme === 'corporate' ? "text-sky-400" :
                                theme === 'minimalist' ? "text-amber-500" :
                                "text-emerald-400"
                            )}>Catalyst AI Intelligence Summary</h4>
                        </div>
                        <p className={cn(
                            "text-lg font-bold leading-relaxed uppercase tracking-tight w-full max-w-none italic break-words whitespace-pre-wrap",
                            theme === 'executive' ? "text-slate-700" :
                            theme === 'emerald' ? "text-emerald-100" :
                            theme === 'cyberpunk' ? "text-fuchsia-100" :
                            theme === 'aurora' ? "text-cyan-100/90" :
                            theme === 'corporate' ? "text-slate-300" :
                            theme === 'minimalist' ? "text-stone-300" :
                            "text-white"
                        )}>
                            {dashboard.config.find(w => w.type === 'summary').notes}
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}
